version: '3.8'

services:
  app:
    image: my-spring-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mssql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql-db:1433;databaseName=mydb;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=ben
      - SPRING_DATASOURCE_PASSWORD=12345678

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "12345678"
      ACCEPT_EULA: "Y"
    restart: always
