version: '3.8'

services:
  app:
    image: my-spring-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://host.docker.internal:53110;databaseName=english;integratedSecurity=false;encrypt=false;
      - SPRING_DATASOURCE_USERNAME=ben
      - SPRING_DATASOURCE_PASSWORD=123
      - GEMINI_URL=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=
      - GEMINI_KEY=AIzaSyDmTI5gNKzvQq9tjlCyISMGePybuQnTWAM